### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by khannaekta**
- [ ] Add the module name, JIRA# to PR/commit and description.
- [ ] Add tests for the change.

### CODE REVIEW

**Comment by khannaekta** [comment]
retest this please

**Comment by kaknikhil** [comment]
retest this please

**Comment by kaknikhil** [comment]
retest this please

**Comment by kaknikhil** [comment]
test this please

**Comment by khannaekta** [comment]
Closing test PR

**Comment by kaknikhil** [comment]
test comment

**Comment by kaknikhil** [comment]
test this please

**Pull request merged**
