### PR TITLE
minor update to summary() user docs

### PR DESCRIPTION
**Pull request by fmcquillan99**
to finish off
https://issues.apache.org/jira/browse/MADLIB-1167

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/319/

**Comment by jingyimei** [comment]
Jekins OK to test

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/320/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/321/

**Comment by iyerr3** [comment]
+1

**Pull request closed without merging**
