### PR TITLE
Internal: Add function to check column type for 1D array

### PR DESCRIPTION
**Pull request by ArvindSridhar**
Added a db_utils function to check whether a column of type array contains 1D arrays only

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/553/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/554/

**Comment by iyerr3** [comment]
Few comments: 
1. The query would read better if it is setup to return a boolean i.e. using `array_upper(..., 2) IS NULL` instead of converting the integer output to bool in Python. 
2. My request in #291 for moving this to a separate commit was for the `plpy_mock.py_in` file since that looks like an independent work. This function is minor enough that it can be kept in #291. 
3. The unit test for this function isn't really testing anything except the last line in the function. That also becomes moot if comment 1. is accepted. Considering this, I suggest we don't have the unit test for this function (at least not in the form it currently is).

**Comment by ArvindSridhar** [comment]
I changed the query but was wondering: since we are now returning just result[0]['n_y'] in python, could this cause problems if our functions calling this expect a python boolean output, while this function outputs a SQL boolean which gets converted into a python string?

**Comment by iyerr3** [comment]
That's a valid concern. You could return bool(result[0]['n_y']) to ensure a
bool output instead of a string (though I believe the SPI ensures that
boolean from SQL is returned as bool in Python).

>

**Comment by iyerr3** [comment]
Yeah, the unit tests are unnecessary after this change. I vote to remove
them, with just the function added back to the original PR.

**Comment by ArvindSridhar** [comment]
Sounds good. Just pushed a commit to this PR, will rebase and add back the original function to the original vec2cols PR tomorrow

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/557/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/558/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/559/

**Comment by ArvindSridhar** [comment]
PR ready to be closed, changes made elsewhere already

**Pull request closed without merging**
