### PR TITLE
Bake LaTex into postgres9.6 latest docker image

### PR DESCRIPTION
**Pull request by jingyimei**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/239/

**Comment by jingyimei** [comment]
Jenkins ok to test.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/244/

**Comment by njayaram2** [comment]
LGTM.

**Pull request closed without merging**
