### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by kinow**
Hi, a few typos found. Not a native speaker, so happy if someone else takes a more careful look at these changes.

Cheers
Bruno

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/727/

**Comment by kaknikhil** [comment]
@kinow Thanks for the PR . LGTM

**Comment by kaknikhil** [comment]
Code has been merged in. closing this PR https://github.com/apache/madlib/commit/d98e7a614ed785f22acc132cd8f076f29bcce493

**Comment by kinow** [comment]
Sure. Done. Thanks!

**Pull request closed without merging**
