### PR TITLE
Release: Upgrade to v1.13

### PR DESCRIPTION
**Pull request by iyerr3**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/309/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/310/

**Comment by orhankislal** [comment]
Tested src and binary upgrades with success and fail scenarios. LGTM +1

**Comment by fmcquillan99** [comment]
Has greenplum 4.3.x testing be completed as well?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/311/

**Comment by iyerr3** [comment]
Upgrade has been tested with postgres 9.6 and greenplum 4.3, 5.0. Merging this PR.

**Pull request closed without merging**
