### PR TITLE
Build: Update to use PYXB_VERSION 1.2.6 (MADLIB-1103).

### PR DESCRIPTION
**Pull request by edespino**
o The MADlib PyXB GPL patch is no longer needed.

o The following has been pushed in PyXB 1.2.6 release:

    https://github.com/pabigot/pyxb/issues/77

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/257/

**Comment by fmcquillan99** [comment]
The content of 
https://github.com/apache/madlib/blob/master/licenses/third_party/PyXB_v1.2.3.txt
looks OK but I suggest you might want to rename the file to PyXB_v1.2.6.txt to reflect the updated version number.

I don’t see any changes required in the LICENSE file
https://github.com/apache/madlib/blob/master/LICENSE

**Comment by edespino** [comment]
@fmcquillan99 - I have updated the license file name as you suggested (PyXB_v1.2.6.txt). I have also added a v1.13 section in RELEASE_NOTES to highlight the PyXB update.

**Comment by fmcquillan99** [comment]
LGTM

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/258/

**Pull request closed without merging**
