### PR TITLE
Fix incorrect dict expansion in table header

### PR DESCRIPTION
**Pull request by iyerr3**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/534/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/541/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/542/

**Comment by fmcquillan99** [comment]
This latest commit makes the following changes to use docs:

1) clarify cv for SVM and add user examples
2) clarify cv for elastic net and fix user examples
3) correct rmse calc in MLP

@rahiyer kindly review and correct and merge.

As for testing the CV output:  LGTM

```
SELECT * FROM abalone_svm_gaussian_regression_cv ORDER BY mean_score DESC;
 init_stepsize | lambda |   mean_score   | std_dev_score  
---------------+--------+----------------+----------------
           1.0 |   0.01 | -4.06711568585 | 0.435966381366
           1.0 |    0.1 | -4.08068428345 |  0.44660797513
           1.0 |    0.5 | -4.52576046087 |  0.20597876382
          0.01 |   0.01 | -11.0231044189 | 0.739956548721
          0.01 |    0.1 | -11.0244799274 | 0.740029346709
          0.01 |    0.5 | -11.0305445077 | 0.740350338532
(6 rows)
```

**Pull request closed without merging**
