### PR TITLE
mini-batch user docs

### PR DESCRIPTION
**Pull request by fmcquillan99**
This commit is for the preprocessor user docs.

MLP user doc updates to follow in subsequent commit.

Can someone please review this content?  thx

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/428/

**Comment by fmcquillan99** [comment]
Main changes:

1) Updated minibatch docs to show use of encoding scalar integer dep var
2) Added minibatch examples and explanations to MLP
3) Reduced the number of redundant examples in MLP examples.

Please have a look and see if it looks OK.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/450/

**Comment by fmcquillan99** [comment]
Main changes:

4. Clarified grouping as per 
https://github.com/apache/madlib/pull/263

This is final change so you can review and merge if it looks good.

**Comment by fmcquillan99** [comment]
OK done now

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/454/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/455/

**Pull request closed without merging**
