### PR TITLE
Docs: Reference "current" PostgreSQL docs instead of EOL versions (MADLIB-1153).

### PR DESCRIPTION
**Pull request by edespino**
Reviewers: @rahiyer @fmcquillan99 @orhankislal @njayaram2 @jingyimei

### CODE REVIEW

**Comment by iyerr3** [comment]
There is a minor risk in doing this. GPDB does not support all features in the current Postgres and I believe the documentation is trying to redirect both GPDB and Postgres users.

**Comment by edespino** [comment]
@iyerr3 - Good point. For reference, there are several other references to **current** in *.sql_in files. Maybe we can add a statement up front indicating Greenplum is based on an older PostgreSQL version and to reference appropriate versions as needed.

```
Ack started at Thu Oct  5 14:48:34

ack -i "https://www.postgresql.org/docs"
methods/sketch/src/pg_gp/sketch.sql_in
73:@note This is a [User Defined Aggregate](https://www.postgresql.org/docs/current/static/xaggr.html)
185:@note This is a [User Defined Aggregate](https://www.postgresql.org/docs/current/static/xaggr.html)
332:@note This is a [User Defined Aggregate](https://www.postgresql.org/docs/current/static/xaggr.html)

src/ports/postgres/modules/utilities/pivot.sql_in
678:[1] https://www.postgresql.org/docs/current/static/functions-aggregate.html
680:[2] https://www.postgresql.org/docs/current/static/sql-createaggregate.html
682:[3] https://www.postgresql.org/docs/current/static/xaggr.html

src/ports/postgres/modules/utilities/sessionize.sql_in
236:https://www.postgresql.org/docs/8.4/static/datatype-datetime.html

Ack finished at Thu Oct  5 14:48:34

```

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/254/

**Comment by edespino** [comment]
@rahiyer - Collaborating with Lisa Owen (@lisakowen - providing excellent editorial know-how), I have added the following note to the Pivot Literature link section:

```
NOTE: The following links refer to documentation resources for the
current PostgreSQL database version. Depending upon your database
platform version, you may need to change "current" references in the
links to your database version.

If your database platform uses the Greenplum Database (or related
variants), please check with the project community and/or your
database vendor to identify the PostgreSQL version it is based on.
```

**Comment by iyerr3** [comment]
Looks great.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/255/

**Comment by edespino** [comment]
@fmcquillan99 - I have made the corresponding change to Path and Sessionize Literature sections.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/256/

**Comment by fmcquillan99** [comment]
LGTM

**Pull request closed without merging**
