### PR TITLE
Multiple: Remove support for HAWQ from all modules

### PR DESCRIPTION
**Pull request by iyerr3**
With HAWQ support removed over the past few versions, we can eliminate
all the code that were specifically written for that port. This
includes madpack changes for upgrade and reinstall, workarounds in
Graph modules for table updates, and special consideration in Group
Iteration Controller.

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/462/

**Comment by fmcquillan99** [comment]
There is some reference to HAWQ in 
https://github.com/apache/madlib/blob/master/ReadMe_Build.txt
which I don’t see removed in the PR.

Otherwise seems OK though I did not do exhaustive search for other HAWQ references.

**Comment by iyerr3** [comment]
Thanks @fmcquillan99  and @njayaram2 for the review. I've removed the above mentioned references and code in the latest commit.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/471/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/472/

**Pull request closed without merging**
