### PR TITLE
Added a Pull Request Template

### PR DESCRIPTION
**Pull request by hpandeycodeit**
This template will help in creating all the PRs in the same format as per the doc: 

https://cwiki.apache.org/confluence/display/MADLIB/Contribution+Guidelines

### CODE REVIEW

**Comment by khannaekta** [comment]
Thanks for creating this template. In my opinion, to start with, the template could just point to a link to the wiki and we can add the required information as check. Below is a snippet:  

- [ ] Add module name, JIRA# to PR/commit description
- [ ] Add tests for the change
- [ ] Pass dev-check/install-check
Link for [contribution guidelines](https://cwiki.apache.org/confluence/display/MADLIB/Contribution+Guidelines)

**Comment by hpandeycodeit** [comment]
This looks okay too. 
However, `Pass dev-check/install-check` can be flaky at the local machine. 

Or we can add tasks list and provide the format in which the PR description should be made? Something like this?

- [ ] Add module name, JIRA# to PR/commit description in the following format: 


**Module Name:**

**JIRA #:**

**Description:**

- [ ] Have you included tests for the changes?

Please refer to the contribution guidelines for more info.

**Comment by khannaekta** [comment]
I am ok to remove `Pass dev-check/install-check` from the template, since we anyways run Jenkins build for each PR.
I think as an initial commit, it would be good to keep the template simple with a small checklist without outlining any formats and see how that helps for future PRs.

**Comment by hpandeycodeit** [comment]
I have updated it as per the discussion. We can anyways update it later it based on the feedback.

**Comment by fmcquillan99** [comment]
@khannaekta please merge

**Pull request merged**
