### PR TITLE
Release/prep 1.15.1

### PR DESCRIPTION
**Pull request by orhankislal**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/698/

**Comment by fmcquillan99** [comment]
Comments on release notes:

(1)
MADLIB-1171 does not apply to AO tables, maybe a typo in this release note:
"Build: Disable AppendOnly if available (MADLIB-1171, MADLIB-1273).""

(2) 
Missing from release notes:

MADLIB-1278	RPM: Upgrade does not work from 1.15 to 1.15.1
https://issues.apache.org/jira/browse/MADLIB-1278

MADLIB-1262	Error for elastic net when the group column contains no-numeric char
https://issues.apache.org/jira/browse/MADLIB-1262

MADLIB-1279	Missing node for graph in-out degrees
https://issues.apache.org/jira/browse/MADLIB-1279

(3)
This one is marked for 1.15.1 but I don't think it got fixed?
Marginal Regression summary tables are lost after the end of session.
https://issues.apache.org/jira/browse/MADLIB-1276

**Comment by orhankislal** [comment]
Thanks for the comments. @fmcquillan99 Regarding MADLIB-1171. The following commit about AO tables references this JIRA even though they are not related https://github.com/madlib/madlib/commit/3db98babe3326fb5e2cd16d0639a2bef264f4b04. It is very strange because the JIRA activity does not show that commit but it has no trouble catching the mention your comment.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/701/

**Pull request closed without merging**
