### PR TITLE
Statistics: Add grouping support for correlation functions

### PR DESCRIPTION
**Pull request by orhankislal**
JIRA: MADLIB-1128

This commit adds grouping support to correlation and covariance
functions in MADlib stats. Changes include relevant queries to do the
same.
This commit also has refactor changes to a helper function in
utilities.py_in.

Co-authored-by: Jingyi Mei <jmei@pivotal.io>
Co-authored-by: Nikhil Kak <nkak@pivotal.io>
Co-authored-by: Nandish Jayaram <njayaram@apache.org>

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/470/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/473/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/474/

**Comment by fmcquillan99** [comment]
(1)
```
DROP TABLE IF EXISTS example_data_output, example_data_output_summary;
SELECT madlib.correlation( 'example_data',
                           'example_data_output',
                           'temperature, humidity'
                         );
```
produces
```
INFO:  ['temperature', 'humidity']
CONTEXT:  PL/Python function "correlation"
-[ RECORD 1 ]----------------------------------------------------------------
correlation | Summary for 'correlation' function
            | Output table = example_data_output
            | Producing correlation for columns: ['temperature', 'humidity']
            | Total run time = ('example_data_output', 2, 0.2568531036376953)
```
which looks OK, but

```
DROP TABLE IF EXISTS example_data_output, example_data_output_summary;
SELECT madlib.covariance( 'example_data',
                          'example_data_output',
                          'temperature, humidity'
                         );
```
produces
```
INFO:  ['temperature', 'humidity']
CONTEXT:  PL/Python function "covariance"
-[ RECORD 1 ]----------------------------------------------------------------
covariance | Summary for 'correlation' function
           | Output table = example_data_output
           | Producing correlation for columns: ['temperature', 'humidity']
           | Total run time = ('example_data_output', 2, 0.27153897285461426)
```
but it should say `Summary for 'covariance' function`

(2)
Above output should list groups if grouping is used, currently it does not.

(3)
Is it intentional to print the INFO message out every time that the correlation/covariance functions
is run?

**Comment by fmcquillan99** [comment]
Also wondering what the nature of the testing is to ensure that covariance and correlation are being calculated properly with the added groups?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/476/

**Comment by orhankislal** [comment]
Thanks for your comments Frank. Regarding the accuracy, I have tested the code with multiple groups from multiple grouping columns with hand-calculated values (as seen in the install-check). I have also tried a larger dataset (600 columns). I have duplicated the data to create multiple columns and checked to see if the results match across groups. Please let us know if you have any other suggestions.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/478/

**Comment by fmcquillan99** [comment]
Thanks for the explanation.

I pushed one additional small commit that changes the name of the module from "Pearson's Correlation" to "Covariance and Correlation" , which is more descriptive of that what this module does.

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/madlib-pr-build/479/

**Pull request closed without merging**
